# Generated by Django 6.0 on 2025-12-04 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id_carro', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=7, unique=True)),
                ('ano', models.CharField(verbose_name=4)),
                ('status', models.CharField(choices=[('Livre', 'Livre'), ('Alugado', 'Alugado'), ('Manutenção', 'Manutenção')], default='Livre')),
            ],
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cnh', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=13)),
                ('endereco', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Aluguel',
            fields=[
                ('id_aluguel', models.AutoField(primary_key=True, serialize=False)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Alugueis_registrados', to=settings.AUTH_USER_MODEL)),
                ('carro_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concessionaria.carro')),
                ('perfil_cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concessionaria.perfilcliente')),
            ],
        ),
    ]
