# Generated by Django 6.0 on 2025-12-04 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='carro_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='concessionaria.carro'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='perfil_cliente_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alugueis', to='concessionaria.perfilcliente'),
        ),
        migrations.AlterField(
            model_name='perfilcliente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
