# Generated by Django 6.0 on 2025-12-12 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concessionaria', '0002_alter_aluguel_carro_id_alter_aluguel_funcionario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluguel',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.RenameField(
            model_name='aluguel',
            old_name='carro_id',
            new_name='carro',
        ),
        migrations.RenameField(
            model_name='aluguel',
            old_name='perfil_cliente_id',
            new_name='perfil_cliente',
        ),
        migrations.RemoveField(
            model_name='aluguel',
            name='id_aluguel',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='id_carro',
        ),
        migrations.RemoveField(
            model_name='perfilcliente',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='aluguel',
            name='atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluguel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='carro',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='perfilcliente',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aluguel',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carro',
            name='ano',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='carro',
            name='status',
            field=models.CharField(choices=[('Livre', 'Livre'), ('Alugado', 'Alugado'), ('Manutenção', 'Manutenção')], default='Livre', max_length=20),
        ),
    ]
